### ISSUE TITLE
worker.ts:6 Uncaught SyntaxError: Unexpected token 'export' (at worker.ts:6:1)

### ISSUE THREAD

**Issue by xiaoxixi6633** [developit/web-worker#33]
worker.ts:6 Uncaught SyntaxError: Unexpected token 'export' (at worker.ts:6:1)
// worker.ts
export const loginEvent = () => {
  console.log(123);
};

**Comment by developit** [comment]
you're missing `{type: 'module'}` as the second argument to `new Worker(..)`.
